// Generated by gencpp from file scan/LidarDatasRequest.msg
// DO NOT EDIT!


#ifndef SCAN_MESSAGE_LIDARDATASREQUEST_H
#define SCAN_MESSAGE_LIDARDATASREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scan
{
template <class ContainerAllocator>
struct LidarDatasRequest_
{
  typedef LidarDatasRequest_<ContainerAllocator> Type;

  LidarDatasRequest_()
    : scanDataRequest()  {
    }
  LidarDatasRequest_(const ContainerAllocator& _alloc)
    : scanDataRequest(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _scanDataRequest_type;
  _scanDataRequest_type scanDataRequest;




  typedef boost::shared_ptr< ::scan::LidarDatasRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scan::LidarDatasRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LidarDatasRequest_

typedef ::scan::LidarDatasRequest_<std::allocator<void> > LidarDatasRequest;

typedef boost::shared_ptr< ::scan::LidarDatasRequest > LidarDatasRequestPtr;
typedef boost::shared_ptr< ::scan::LidarDatasRequest const> LidarDatasRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scan::LidarDatasRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scan::LidarDatasRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scan::LidarDatasRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scan::LidarDatasRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scan::LidarDatasRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scan::LidarDatasRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan::LidarDatasRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scan::LidarDatasRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scan::LidarDatasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e7a70afeed50b1374f71a7507da6c78";
  }

  static const char* value(const ::scan::LidarDatasRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e7a70afeed50b13ULL;
  static const uint64_t static_value2 = 0x74f71a7507da6c78ULL;
};

template<class ContainerAllocator>
struct DataType< ::scan::LidarDatasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scan/LidarDatasRequest";
  }

  static const char* value(const ::scan::LidarDatasRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scan::LidarDatasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string scanDataRequest\n\
";
  }

  static const char* value(const ::scan::LidarDatasRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scan::LidarDatasRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scanDataRequest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarDatasRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scan::LidarDatasRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scan::LidarDatasRequest_<ContainerAllocator>& v)
  {
    s << indent << "scanDataRequest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.scanDataRequest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCAN_MESSAGE_LIDARDATASREQUEST_H
